#!/usr/bin/perl
###########################################
# xx -- 
# Mike Schilli, 2004 (m@perlmeister.com)
###########################################
use warnings;
use strict;

use Sysadm::Install qw(ask pick);

my $name = ask("Type in your name", "Joe");
print "Your name is $name.\n";

my $fruit = pick("Pick a fruit", ["apple", "pear", "pineapple"], 3);
print "Your picked $fruit.\n";

